### ISSUE TITLE
skill order return null

### ISSUE THREAD

**Issue by ahmedsafadii** [joel1st/championweb#61]
problem with some champions like Kha'Zix and Ryze

http://api.champion.gg/champion/Khazix?api_key=??

<img width="392" alt="screen shot 2016-10-11 at 6 21 05 pm" src="https://cloud.githubusercontent.com/assets/6974081/19276581/80195a28-8fdf-11e6-82fd-f936c711ee14.png">

**Comment by abaltra** [comment]
Hi! The problem was with champions that when leveling up, they add modifiers to other skills (like Kha's evolution points), but I couldn't find anything wrong with Ryze's :/

The case I mentioned is fixed and should be going live sometime today. Do you have any more info on to Ryze issue?

**Comment by ahmedsafadii** [comment]
btw found null items for TOP tahmkench :(
<img width="701" alt="screen shot 2016-10-11 at 9 14 14 pm" src="https://cloud.githubusercontent.com/assets/6974081/19282625/c87be21e-8ff7-11e6-9b4e-ff55f34b9ce6.png">

and about ryze

<img width="662" alt="screen shot 2016-10-11 at 9 16 26 pm" src="https://cloud.githubusercontent.com/assets/6974081/19282680/01490022-8ff8-11e6-9f01-190f48a476d4.png">

there's missing R ^^"

**Comment by ahmedsafadii** [comment]
champions with next ids got no full items for highestWinPercent

223
3
74
133
6
266
33
36
48
133
14
31
111

champions got no runes for highestWinPercent

33

champions got no skills for highestWinPercent

121

champions got no mastery for highestWinPercent

3

^^" that's all

**Comment by abaltra** [comment]
@ahmedsafadii The Ryze thing is that the last rework of the champ (let's hope it's the last :P) only has 2 levels for the ult and 6 levels for Q.

About the other champions not having some elements, that's because the current data doesn't have enough critical mass to calculate a statistically relevant value for it. For example in the case of TK top, there's a very small amount of players that use it and out of those, the builds vary a lot, so the most repeated build doesn't repeat itself enough times to be caught by our threshold.
