### ISSUE TITLE
[Question] Region Selector

### ISSUE THREAD

**Issue by yogupoa** [joel1st/championweb#62]
Hi guys!

As you can see at [Year in Review](http://na.leagueoflegends.com/en/featured/year-in-review) each region plays its own way.
So I thought ... if our beloved champion GG had a region selector?
We could know the METAGAME of our region.
Is this viable?

**Comment by pfugate** [comment]
Hi @yogupoa!

Thanks so much for your suggestion. It's something we have been thinking about for quite sometime, but there are some statistical/technical hurdles to overcome for something on a region by region basis to be effective. One of the changes that is coming to champion.gg is the ability to select the ELO you are looking at, since the META-game is different per ELO, and there are tons of players in each ELO. One of the limitations of a per region filter is that there is not an even distribution of games played per region. As we perfect our strategies for gathering ideal data, we hope to be able to bring more features like this to champion.gg. Thanks again!

Best,
@pfugate
