### ISSUE TITLE
Question: how is the data used scraped from the API

### ISSUE THREAD

**Issue by AdamKilbo** [joel1st/championweb#69]
Hello, I'm kinda new to using the Riot API and I'm curious how you get all data for every game (or at least plat+ games). Is there a way that you can assure that you grabbing data from all possible games? 

Currently the only way that I know about to grab all data is either by scraping match IDs through a summoners match history (problems with getting out of date matches and dead ends if you do a crawler style program) or incrementing match ID by one to see if the next ID exists (I can see problem with non sequential match IDs and non existent match IDs if you are at an ID greater than what has been created).

Thanks for your time!

**Comment by jjmaldonis** [comment]
Hey hopefully the real devs respond to this, but I'd just like to mention that the Rioters over on the API Forums have expressly asked people _not_ to increment match IDs when trying to scrape all matches. This puts an _enormous_ load on their servers for various reasons, in addition to the fact that the vast majority of games played are customs (maybe because of bots or test games?) so you will only care about a fraction of the match IDs that actually return without errorring.

If you haven't talked with the people over on the API Forums, I highly encourage you to do that because they are very knowledgable.

**Comment by pfugate** [comment]
Hi @AdamKilbo,

I'm a dev for TSM (the current owners of Champion.gg), and wanted to help answer your question. What @jjmaldonis said is correct. Riot strongly discourages trying to get matches by incrementing the match ID. The only way to get verifiable match id's is from the summoners matchlist endpoint. It is possible to spider to get all the summoners that play from just a handful of summoner Ids in each region (we've done just that).

The other key issue here to under stand is the sheer scale of matches played everyday. Each region sees in excess of 2 million ranked matches per day (so that'd be around 20 million champions). Getting one crawler to parse more than 10 matches a second (even in parallel code) is very difficult.  So to get all matches for just one region you'd have to have a pretty massive system. 

The approach Champion.gg and other sites (such as op.gg) use is whats called sampling. You take a representative sample of players and use that to derive play statistics. Also, the Riot Dev forums are a great place to ask questions!

Hope this helps.

**Comment by AdamKilbo** [comment]
Thanks! I really appreciate the feedback, it's really helped me put together a plan for my own programs.
