### ISSUE TITLE
db/championgg  stop update?

### ISSUE THREAD

**Issue by playcode001** [joel1st/championweb#75]
db/championgg  stop update?

**Comment by amitbend** [comment]
Any updates guys?
The new API seems to be not updated as well
@kyle-young

**Comment by playcode001** [comment]
![image](https://user-images.githubusercontent.com/5078044/28768494-6be767e0-760a-11e7-9ba5-3ed6bfd2456a.png)
Http://champion.gg data has been updated, why not update the DB data on github, hope the author to continue to update.

**Comment by playcode001** [comment]
![image](https://user-images.githubusercontent.com/5078044/28768700-353e793a-760b-11e7-8ac7-edf03f08df55.png)
Http://champion.gg data has been updated, why not update the DB data on github, hope the author to continue to update.

**Comment by pfugate** [comment]
Hi @playcode001 and @amitbend 

We've moved to a streaming data model, meaning that the data is computed continuously instead of in chunks. Because of this, and the changes to the data structures internally, we are no longer updating this repo with new data. You can access all of the current data through the champion.gg API, by going to api.champion.gg.
